### ISSUE TITLE
R-4.0-branch R version mis-match in description

### ISSUE THREAD

**Issue by hrbrmstr** [s-u/R-mac-dev#8]
The **R-4.0-branch** is the following as of the submission timestamp of this GH issue:

```
R-4.0-branch
4.1.0 Under development (unstable)
(2021/03/29, r80130)
```

![image](https://user-images.githubusercontent.com/509878/113130288-e88e9d00-91e9-11eb-899b-87f79a15aeb2.png)

It is indeed R-devel, though.

**Comment by s-u** [comment]
Thanks! There appears to be a race condition where two nightly builds start at the same time (for as yet unknown reason) which means one build of the R-4.0-branch fails immediately but then carries on to R-devel which the other one is still at R-4.0-branch. Since the builds have to be started using LaunchAgents it's a bit more tricky to debug. The real fix is to make builds fully independent (temporary build directories etc.), but that will require quite a bit of work, because currently some parts work off the `/Library/Frameworks` location which is global and thus cannot be used with parallel builds. A quick fix is to stop the job if another one is running.

**Comment by coatless** [comment]
> A quick fix is to stop the job if another one is running.

Why not stagger the start times of the jobs in addition checking if a "lock file" is present?

**Comment by s-u** [comment]
There is only one start time - the builds are done in series using one script, hence the mystery - they are not supposed to be running multiple jobs, but somehow due to the way launchctl works it appears that the script gets called twice in parallel...

**Comment by s-u** [comment]
I believe this has been fixed... hopefully ;)
